stages:
  - build

build_tex:
  image: texlive/texlive
  tags:
    - docker
  stage: build
  artifacts:
    paths:
      - 'main.pdf'
  script:
    - pdflatex main.tex
    - biber main
    - pdflatex main.tex
    - pdflatex main.tex
