name: ci-build

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive

    steps:
      - uses: actions/checkout@v2
      - name: Build LaTeX pdf-output
        run: |
          pdflatex main.tex
          biber main
          pdflatex main.tex
          pdflatex main.tex

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: main.pdf
